# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvj7idWi0JsQqe-eDktQoi5PzvmiowaO
"""

import pandas as pd
baza={
    "FISH":['Ismatullayeva Mohidil' , 'Ismatullayev Dilmurod' , 'Jo`raqo`ziyev Azizbek' , 'Bakirova Farangiz' , 'Ismatullayev Muhammadsodiq'],
    "Yoshi":['16' , '14' , '12' , '17' , '9'],
    "Jinsi":['qiz bola' , 'o`g`il bola' , 'o`g`il bola' , 'qiz bola' , 'o`g`il bola'],
    "Maktabi":['akademiya' , '53' , 'Prezident' , '32' , '11']
}
df=pd.DataFrame(baza)
print(df)

df['Yoshi'] = pd.to_numeric(df['Yoshi'], errors='coerce')
filtr = df[(df['Jinsi'] == "o`g`il bola") & (df['Yoshi'] > 9)]
print(filtr)